### ISSUE TITLE
traceback

### ISSUE THREAD

**Issue by hngocuyen** [PoZeep/PycFlower#1]
Traceback (most recent call last):
  File "/storage/emulated/0/enpj/k-fuscator/dec/PycFlower/main.py", line 22, in <module>
    main()
  File "/storage/emulated/0/enpj/k-fuscator/dec/PycFlower/main.py", line 14, in main
    file = PycFlowerTools.main(f, version)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/emulated/0/enpj/k-fuscator/dec/PycFlower/PycFlowerTools.py", line 197, in main
    file += bytes(org_file[code_attribute[i]['index'] + code_attribute[i]['len']:])
                                          ^
UnboundLocalError: cannot access local variable 'i' where it is not associated with a value

**Comment by PoZeep** [comment]
According to your error message, I guess the reason is the python3 version of pyc. If a function is too large, the script inserts the obfuscated bytecode and needs to adjust EXTENDED_ARG. I am sorry that I have not finished writing about this. At present, you can try to convert a function to Writing smaller might solve this problem.

**Comment by hngocuyen** [comment]
ah bug in python3.11
